"""add clinical_note kind and details

Revision ID: 2cc000bd2f14
Revises: 5010a389a4bf
Create Date: 2026-06-28 19:03:08.855542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cc000bd2f14'
down_revision: Union[str, Sequence[str], None] = '5010a389a4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_notes', sa.Column('kind', sa.Enum('nota_soap', 'constancia', 'incapacidad', name='clinical_note_kind', native_enum=False, create_constraint=True), server_default='nota_soap', nullable=False, comment='Tipo de documento: nota_soap, constancia o incapacidad.'))
    op.add_column('clinical_notes', sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='Datos snapshot por tipo (JSON portable): constancia/incapacidad guardan aquí nombre del paciente, médico y cédula, fecha de asistencia, diagnóstico/motivo y, para incapacidad, inicio y número de días de reposo. La nota SOAP no lo usa.'))
    # ``op.add_column`` con el enum NO-NATIVO (create_constraint=True) ya crea el CHECK
    # ck_clinical_notes_clinical_note_kind en esta versión de Alembic; no se agrega a mano
    # (hacerlo lo duplicaría). El CHECK acepta exactamente los valores del enum.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_notes', 'details')
    op.drop_column('clinical_notes', 'kind')
    # ### end Alembic commands ###
