"""add consultation diagnoses table

Revision ID: 2e8cb54d1a52
Revises: f5f97d30d43f
Create Date: 2026-06-26 22:31:18.684137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8cb54d1a52'
down_revision: Union[str, Sequence[str], None] = 'f5f97d30d43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Consulta a la que pertenece el diagnóstico.'),
    sa.Column('diagnosis_kind', sa.Enum('primary', 'secondary', 'suspected', name='consultation_diagnosis_kind', native_enum=False, create_constraint=True), nullable=False, comment='Tipo de diagnóstico: principal, secundario o presuntivo.'),
    sa.Column('diagnosis_text', sa.Text(), nullable=False, comment='Texto del diagnóstico o impresión diagnóstica.'),
    sa.Column('coding_system', sa.String(length=80), nullable=True, comment='Sistema de codificación, si se registra (codificación futura).'),
    sa.Column('code', sa.String(length=80), nullable=True, comment='Código del diagnóstico, si se registra.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observaciones breves sobre el diagnóstico.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro del diagnóstico.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró el diagnóstico.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última edición, mientras la consulta esté en borrador.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que editó el diagnóstico.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del diagnóstico.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el diagnóstico.'),
    sa.CheckConstraint('(coding_system IS NULL AND code IS NULL) OR (coding_system IS NOT NULL AND code IS NOT NULL)', name=op.f('ck_consultation_diagnoses_coding_pair')),
    sa.CheckConstraint('length(trim(diagnosis_text)) > 0', name=op.f('ck_consultation_diagnoses_diagnosis_text_not_blank')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_consultation_diagnoses_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_consultation_diagnoses_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_consultation_diagnoses_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_consultation_diagnoses_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_diagnoses'))
    )
    op.create_index('ix_consultation_diagnoses_consultation', 'consultation_diagnoses', ['consultation_id'], unique=False)
    op.create_index('ix_consultation_diagnoses_consultation_kind', 'consultation_diagnoses', ['consultation_id', 'diagnosis_kind'], unique=False)
    op.create_index('ix_consultation_diagnoses_kind', 'consultation_diagnoses', ['diagnosis_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consultation_diagnoses_kind', table_name='consultation_diagnoses')
    op.drop_index('ix_consultation_diagnoses_consultation_kind', table_name='consultation_diagnoses')
    op.drop_index('ix_consultation_diagnoses_consultation', table_name='consultation_diagnoses')
    op.drop_table('consultation_diagnoses')
    # ### end Alembic commands ###
