"""add clinical_notes table

Revision ID: 5010a389a4bf
Revises: 4f4c24418e8a
Create Date: 2026-06-28 18:47:26.737556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5010a389a4bf'
down_revision: Union[str, Sequence[str], None] = '4f4c24418e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente al que pertenece la nota (derivado de la consulta).'),
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Consulta de la que se compone la nota SOAP.'),
    sa.Column('subjective', sa.Text(), nullable=True, comment='Sección S (Subjetivo): motivo, padecimiento, interrogatorio.'),
    sa.Column('objective', sa.Text(), nullable=True, comment='Sección O (Objetivo): exploración física y hallazgos.'),
    sa.Column('assessment', sa.Text(), nullable=True, comment='Sección A (Análisis): valoración/impresión diagnóstica.'),
    sa.Column('plan', sa.Text(), nullable=True, comment='Sección P (Plan): tratamiento, indicaciones, seguimiento.'),
    sa.Column('status', sa.Enum('draft', 'approved', name='clinical_note_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado de la nota: draft (borrador) o approved (aprobada por el médico).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la nota.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró la nota.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó la nota.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la nota.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la nota.'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_clinical_notes_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_clinical_notes_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_clinical_notes_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_notes_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_clinical_notes_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_notes'))
    )
    op.create_index('ix_clinical_notes_consultation', 'clinical_notes', ['consultation_id'], unique=False)
    op.create_index('ix_clinical_notes_patient', 'clinical_notes', ['patient_id'], unique=False)
    op.create_index('ix_clinical_notes_patient_created_at', 'clinical_notes', ['patient_id', 'created_at'], unique=False)
    op.create_index('ix_clinical_notes_status', 'clinical_notes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clinical_notes_status', table_name='clinical_notes')
    op.drop_index('ix_clinical_notes_patient_created_at', table_name='clinical_notes')
    op.drop_index('ix_clinical_notes_patient', table_name='clinical_notes')
    op.drop_index('ix_clinical_notes_consultation', table_name='clinical_notes')
    op.drop_table('clinical_notes')
    # ### end Alembic commands ###
