"""add study_orders and clinical_tasks

Revision ID: 6bb02a84ca2a
Revises: 84413285ba37
Create Date: 2026-06-28 15:33:49.756250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb02a84ca2a'
down_revision: Union[str, Sequence[str], None] = '84413285ba37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Usuario dueño/responsable de la tarea.'),
    sa.Column('patient_id', sa.UUID(), nullable=True, comment='Paciente relacionado con la tarea, si aplica.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título de la tarea.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción o detalle de la tarea.'),
    sa.Column('due_at', sa.DateTime(), nullable=True, comment='Fecha y hora de vencimiento, si aplica.'),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='clinical_task_priority', native_enum=False, create_constraint=True), server_default='medium', nullable=False, comment='Prioridad de la tarea: baja, media o alta.'),
    sa.Column('status', sa.Enum('open', 'done', 'cancelled', name='clinical_task_status', native_enum=False, create_constraint=True), server_default='open', nullable=False, comment='Estado de la tarea: abierta, hecha o cancelada.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro de la tarea.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que creó la tarea.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó la tarea.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la tarea.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la tarea.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_clinical_tasks_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_clinical_tasks_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_clinical_tasks_owner_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_tasks_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_clinical_tasks_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_tasks'))
    )
    op.create_index('ix_clinical_tasks_due_at', 'clinical_tasks', ['due_at'], unique=False)
    op.create_index('ix_clinical_tasks_owner', 'clinical_tasks', ['owner_id'], unique=False)
    op.create_index('ix_clinical_tasks_owner_status', 'clinical_tasks', ['owner_id', 'status'], unique=False)
    op.create_index('ix_clinical_tasks_patient', 'clinical_tasks', ['patient_id'], unique=False)
    op.create_index('ix_clinical_tasks_status', 'clinical_tasks', ['status'], unique=False)
    op.create_table('study_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente para quien se ordena el estudio.'),
    sa.Column('ordered_by', sa.UUID(), nullable=False, comment='Médico que ordena el estudio.'),
    sa.Column('study_name', sa.String(length=255), nullable=False, comment='Nombre del estudio solicitado.'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='Código del estudio (estilo LOINC), si aplica.'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Motivo clínico de la solicitud.'),
    sa.Column('ordered_at', sa.DateTime(), nullable=False, comment='Fecha y hora en que se ordenó el estudio.'),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'resulted', 'cancelled', name='study_order_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False, comment='Estado: pendiente, en proceso, con resultado o cancelado.'),
    sa.Column('result_lab_result_id', sa.UUID(), nullable=True, comment='Resultado de laboratorio estructurado vinculado, cuando el estudio se resuelve.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro de la orden.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró la orden.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó la orden.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la orden.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la orden.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_study_orders_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_study_orders_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ordered_by'], ['doctors.id'], name=op.f('fk_study_orders_ordered_by_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_study_orders_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_lab_result_id'], ['lab_results.id'], name=op.f('fk_study_orders_result_lab_result_id_lab_results'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_study_orders_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_orders'))
    )
    op.create_index('ix_study_orders_ordered_at', 'study_orders', ['ordered_at'], unique=False)
    op.create_index('ix_study_orders_patient', 'study_orders', ['patient_id'], unique=False)
    op.create_index('ix_study_orders_patient_ordered_at', 'study_orders', ['patient_id', 'ordered_at'], unique=False)
    op.create_index('ix_study_orders_status', 'study_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_study_orders_status', table_name='study_orders')
    op.drop_index('ix_study_orders_patient_ordered_at', table_name='study_orders')
    op.drop_index('ix_study_orders_patient', table_name='study_orders')
    op.drop_index('ix_study_orders_ordered_at', table_name='study_orders')
    op.drop_table('study_orders')
    op.drop_index('ix_clinical_tasks_status', table_name='clinical_tasks')
    op.drop_index('ix_clinical_tasks_patient', table_name='clinical_tasks')
    op.drop_index('ix_clinical_tasks_owner_status', table_name='clinical_tasks')
    op.drop_index('ix_clinical_tasks_owner', table_name='clinical_tasks')
    op.drop_index('ix_clinical_tasks_due_at', table_name='clinical_tasks')
    op.drop_table('clinical_tasks')
    # ### end Alembic commands ###
