"""add clinical domain and platform_setup tables

Revision ID: 6dafd4d73445
Revises: ebf33ec14f29
Create Date: 2026-06-26 20:33:18.406720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dafd4d73445'
down_revision: Union[str, Sequence[str], None] = 'ebf33ec14f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False, comment='Tabla o tipo de entidad afectada por el evento.'),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='Identificador del registro afectado.'),
    sa.Column('action', sa.String(length=120), nullable=False, comment='Acción realizada, por ejemplo consultation_finalized o prescription_approved.'),
    sa.Column('actor_user_id', sa.UUID(), nullable=True, comment='Usuario que ejecutó la acción. Puede ser nulo para procesos automáticos del sistema.'),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='Resumen de los campos modificados.'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Motivo del evento, cuando aplique.'),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora del evento de auditoría.'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_audit_events_actor_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_user', 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_occurred_at', 'audit_events', ['occurred_at'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Usuario al que pertenece este perfil médico. Un usuario sólo puede tener un perfil de médico.'),
    sa.Column('professional_name', sa.String(length=255), nullable=False, comment='Nombre mostrado en consultas, recetas y documentos clínicos.'),
    sa.Column('professional_title', sa.String(length=120), nullable=True, comment='Título profesional mostrado, por ejemplo Dr., Dra. o Médico Cirujano.'),
    sa.Column('professional_license_number', sa.String(length=80), nullable=False, comment='Cédula profesional principal.'),
    sa.Column('specialty', sa.String(length=160), nullable=True, comment='Especialidad médica, si aplica.'),
    sa.Column('specialty_license_number', sa.String(length=80), nullable=True, comment='Cédula de especialidad, si aplica.'),
    sa.Column('professional_phone', sa.String(length=40), nullable=True, comment='Teléfono profesional del médico.'),
    sa.Column('professional_email', sa.String(length=255), nullable=True, comment='Correo profesional del médico.'),
    sa.Column('clinic_name', sa.String(length=255), nullable=True, comment='Nombre de clínica o consultorio.'),
    sa.Column('office_address', sa.Text(), nullable=True, comment='Dirección profesional o de consultorio.'),
    sa.Column('office_phone', sa.String(length=40), nullable=True, comment='Teléfono del consultorio.'),
    sa.Column('prescription_footer', sa.Text(), nullable=True, comment='Texto o leyenda que aparecerá en recetas.'),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='record_status', native_enum=False, create_constraint=True), nullable=False, comment='Sólo médicos activos pueden finalizar consultas, revisar historia clínica o aprobar recetas.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de alta del perfil médico.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que creó el perfil médico.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del perfil médico.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el perfil médico.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_doctors_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_doctors_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_doctors_updated_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_doctors_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors')),
    sa.UniqueConstraint('professional_license_number', name='uq_doctors_professional_license_number'),
    sa.UniqueConstraint('user_id', name='uq_doctors_user_id')
    )
    op.create_index('ix_doctors_status', 'doctors', ['status'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_number', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='Número interno de expediente generado por la base de datos (identity). Inmutable; el prefijo visual (p. ej. EXP-000123) es de presentación.'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Nombre completo del paciente.'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='Fecha de nacimiento. La edad se calcula a partir de este campo.'),
    sa.Column('sex', sa.Enum('female', 'male', 'other', 'unspecified', name='sex', native_enum=False, create_constraint=True), nullable=False, comment='Sexo registrado para fines clínicos y administrativos.'),
    sa.Column('phone', sa.String(length=40), nullable=True, comment='Teléfono del paciente.'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Correo electrónico del paciente.'),
    sa.Column('address', sa.Text(), nullable=True, comment='Dirección del paciente.'),
    sa.Column('curp', sa.String(length=18), nullable=True, comment='CURP normalizada (mayúsculas, sin espacios). Única entre expedientes no eliminados.'),
    sa.Column('occupation', sa.String(length=160), nullable=True, comment='Ocupación opcional del paciente.'),
    sa.Column('marital_status', sa.String(length=80), nullable=True, comment='Estado civil opcional del paciente.'),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True, comment='Nombre del contacto de emergencia.'),
    sa.Column('emergency_contact_relationship', sa.String(length=120), nullable=True, comment='Parentesco o relación del contacto de emergencia.'),
    sa.Column('emergency_contact_phone', sa.String(length=40), nullable=True, comment='Teléfono de emergencia.'),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='patient_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado administrativo del expediente: active, inactive o archived.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro. Representa el alta del paciente.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró al paciente.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del expediente del paciente.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el expediente del paciente.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_patients_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_patients_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_patients_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('record_number', name='uq_patients_record_number')
    )
    op.create_index('ix_patients_created_at', 'patients', ['created_at'], unique=False)
    op.create_index('ix_patients_full_name', 'patients', ['full_name'], unique=False)
    op.create_index('ix_patients_status', 'patients', ['status'], unique=False)
    op.create_index('uq_patients_curp_active', 'patients', ['curp'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente con la cita médica.'),
    sa.Column('doctor_id', sa.UUID(), nullable=False, comment='Médico asignado a la cita.'),
    sa.Column('scheduled_date', sa.Date(), nullable=False, comment='Fecha programada de la cita.'),
    sa.Column('scheduled_time', sa.Time(), nullable=True, comment='Hora programada de la cita. Puede omitirse cuando el paciente acudirá dentro del horario de consulta.'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Duración estimada de la cita en minutos.'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Motivo de la cita.'),
    sa.Column('internal_notes', sa.Text(), nullable=True, comment='Notas internas sobre la cita.'),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'attended', 'cancelled', 'rescheduled', 'no_show', name='appointment_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado de la cita médica.'),
    sa.Column('rescheduled_from_id', sa.UUID(), nullable=True, comment='Cita original cuando esta cita deriva de una reprogramación.'),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True, comment='Fecha y hora de cancelación de la cita.'),
    sa.Column('cancelled_by', sa.UUID(), nullable=True, comment='Usuario que canceló la cita.'),
    sa.Column('cancellation_reason', sa.Text(), nullable=True, comment='Motivo de cancelación de la cita.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la cita.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró la cita.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó la cita.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Eliminación lógica, sólo para casos administrativos excepcionales.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la cita.'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['user.id'], name=op.f('fk_appointments_cancelled_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_appointments_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_appointments_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_appointments_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], name=op.f('fk_appointments_rescheduled_from_id_appointments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_appointments_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index('ix_appointments_doctor', 'appointments', ['doctor_id'], unique=False)
    op.create_index('ix_appointments_doctor_date_time', 'appointments', ['doctor_id', 'scheduled_date', 'scheduled_time'], unique=False)
    op.create_index('ix_appointments_patient', 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_rescheduled_from', 'appointments', ['rescheduled_from_id'], unique=False)
    op.create_index('ix_appointments_scheduled_date', 'appointments', ['scheduled_date'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_table('medical_history_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente relacionado con esta versión de historia clínica.'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Número consecutivo de versión de historia clínica del paciente.'),
    sa.Column('status', sa.Enum('draft', 'current', 'superseded', name='medical_history_version_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado de la versión: borrador, vigente o sustituida.'),
    sa.Column('family_history', sa.Text(), nullable=True, comment='Antecedentes heredofamiliares.'),
    sa.Column('pathological_history', sa.Text(), nullable=True, comment='Antecedentes personales patológicos.'),
    sa.Column('non_pathological_history', sa.Text(), nullable=True, comment='Antecedentes personales no patológicos.'),
    sa.Column('previous_surgeries', sa.Text(), nullable=True, comment='Cirugías previas.'),
    sa.Column('hospitalizations', sa.Text(), nullable=True, comment='Hospitalizaciones.'),
    sa.Column('relevant_habits_notes', sa.Text(), nullable=True, comment='Narrativa adicional sobre hábitos. El resumen vigente vive en patient_clinical_items.'),
    sa.Column('gyneco_obstetric_history', sa.Text(), nullable=True, comment='Antecedentes gineco-obstétricos, si aplica.'),
    sa.Column('clinical_observations', sa.Text(), nullable=True, comment='Observaciones clínicas generales.'),
    sa.Column('change_reason', sa.Text(), nullable=True, comment='Motivo de creación o actualización de la versión.'),
    sa.Column('reviewed_by_doctor_id', sa.UUID(), nullable=True, comment='Médico que revisó o validó esta versión de historia clínica.'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='Fecha de validación de la historia clínica.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la versión de historia clínica.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que capturó la versión de historia clínica.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última edición mientras la versión sea borrador.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que editó la versión de historia clínica.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Eliminación lógica, sólo permitida en borradores no validados.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la versión de historia clínica.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_medical_history_versions_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_medical_history_versions_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medical_history_versions_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_doctor_id'], ['doctors.id'], name=op.f('fk_medical_history_versions_reviewed_by_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_medical_history_versions_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_history_versions')),
    sa.UniqueConstraint('patient_id', 'version_number', name='uq_medical_history_versions_patient_version')
    )
    op.create_index('ix_medical_history_versions_patient', 'medical_history_versions', ['patient_id'], unique=False)
    op.create_index('ix_medical_history_versions_reviewed_by', 'medical_history_versions', ['reviewed_by_doctor_id'], unique=False)
    op.create_index('ix_medical_history_versions_status', 'medical_history_versions', ['status'], unique=False)
    op.create_index('uq_medical_history_versions_current_patient', 'medical_history_versions', ['patient_id'], unique=True, postgresql_where=sa.text("status = 'current' AND deleted_at IS NULL"))
    op.create_table('medication_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False, comment='Médico propietario de la plantilla de medicamento.'),
    sa.Column('medication_name', sa.String(length=255), nullable=False, comment='Nombre del medicamento.'),
    sa.Column('presentation', sa.String(length=160), nullable=True, comment='Presentación habitual del medicamento.'),
    sa.Column('default_dose', sa.String(length=160), nullable=True, comment='Dosis sugerida.'),
    sa.Column('default_frequency', sa.String(length=160), nullable=True, comment='Frecuencia sugerida.'),
    sa.Column('default_duration', sa.String(length=160), nullable=True, comment='Duración sugerida.'),
    sa.Column('default_instructions', sa.Text(), nullable=True, comment='Indicaciones sugeridas.'),
    sa.Column('use_count', sa.Integer(), nullable=False, comment='Veces que se ha reutilizado la plantilla.'),
    sa.Column('status', sa.Enum('active', 'inactive', name='active_inactive_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado de la plantilla: activa o inactiva.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la plantilla.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que creó la plantilla.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última actualización de la plantilla.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó la plantilla.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la plantilla.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la plantilla.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_medication_templates_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_medication_templates_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_medication_templates_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_medication_templates_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_templates')),
    sa.UniqueConstraint('doctor_id', 'medication_name', 'presentation', name='uq_medication_templates_doctor_medication_presentation')
    )
    op.create_index('ix_medication_templates_doctor', 'medication_templates', ['doctor_id'], unique=False)
    op.create_index('ix_medication_templates_medication_name', 'medication_templates', ['medication_name'], unique=False)
    op.create_index('ix_medication_templates_status', 'medication_templates', ['status'], unique=False)
    op.create_table('patient_clinical_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente al que pertenece el dato clínico importante.'),
    sa.Column('item_type', sa.Enum('allergy', 'chronic_condition', 'current_medication', 'relevant_habit', 'clinical_alert', 'other', name='patient_clinical_item_type', native_enum=False, create_constraint=True), nullable=False, comment='Tipo de dato: alergia, enfermedad crónica, medicamento actual, hábito, alerta clínica u otro.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Nombre del elemento clínico.'),
    sa.Column('details', sa.Text(), nullable=True, comment='Reacción, dosis, frecuencia, descripción o contexto del dato clínico.'),
    sa.Column('severity', sa.Enum('mild', 'moderate', 'severe', 'critical', name='clinical_severity', native_enum=False, create_constraint=True), nullable=True, comment='Severidad leve, moderada, grave o crítica, si aplica.'),
    sa.Column('status', sa.Enum('active', 'inactive', 'resolved', 'suspended', name='clinical_item_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado del dato clínico importante.'),
    sa.Column('started_at', sa.Date(), nullable=True, comment='Inicio conocido del dato clínico, si aplica.'),
    sa.Column('ended_at', sa.Date(), nullable=True, comment='Fin o resolución del dato clínico, si aplica.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro del dato clínico.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que agregó el dato clínico.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó el dato clínico.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del dato clínico.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el dato clínico.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_patient_clinical_items_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_patient_clinical_items_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_clinical_items_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_patient_clinical_items_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_clinical_items'))
    )
    op.create_index('ix_patient_clinical_items_patient', 'patient_clinical_items', ['patient_id'], unique=False)
    op.create_index('ix_patient_clinical_items_patient_type_status', 'patient_clinical_items', ['patient_id', 'item_type', 'status'], unique=False)
    op.create_index('ix_patient_clinical_items_status', 'patient_clinical_items', ['status'], unique=False)
    op.create_index('ix_patient_clinical_items_type', 'patient_clinical_items', ['item_type'], unique=False)
    op.create_table('platform_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Fecha y hora de cierre permanente del Bootstrap HTTP.'),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True, comment='Usuario inicial que completo el Bootstrap HTTP, si aplica.'),
    sa.Column('system_admin_role_id', sa.UUID(), nullable=True, comment='Rol administrador fundacional protegido por el core.'),
    sa.Column('completion_origin', sa.String(), nullable=True, comment='Origen del cierre: bootstrap de producto o instalacion legacy.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del estado de instalacion.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la ultima modificacion.'),
    sa.CheckConstraint("completion_origin is null or completion_origin in ('bootstrap', 'legacy')", name=op.f('ck_platform_setup_ck_platform_setup_completion_origin')),
    sa.CheckConstraint("status in ('pending', 'completed')", name=op.f('ck_platform_setup_ck_platform_setup_status')),
    sa.CheckConstraint('id = 1', name=op.f('ck_platform_setup_ck_platform_setup_singleton')),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['user.id'], name=op.f('fk_platform_setup_completed_by_user_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['system_admin_role_id'], ['role.id'], name=op.f('fk_platform_setup_system_admin_role_id_role'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_setup'))
    )
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente atendido en la consulta.'),
    sa.Column('appointment_id', sa.UUID(), nullable=True, comment='Cita de origen, si la consulta deriva de una cita agendada.'),
    sa.Column('attending_doctor_id', sa.UUID(), nullable=False, comment='Médico tratante de la consulta.'),
    sa.Column('consulted_at', sa.DateTime(), nullable=False, comment='Fecha y hora de la atención médica.'),
    sa.Column('reason_for_visit', sa.Text(), nullable=True, comment='Motivo de consulta.'),
    sa.Column('current_illness', sa.Text(), nullable=True, comment='Padecimiento actual.'),
    sa.Column('interrogation', sa.Text(), nullable=True, comment='Interrogatorio clínico.'),
    sa.Column('physical_examination', sa.Text(), nullable=True, comment='Exploración física.'),
    sa.Column('clinical_assessment', sa.Text(), nullable=True, comment='Valoración o impresión clínica narrativa.'),
    sa.Column('treatment', sa.Text(), nullable=True, comment='Tratamiento general.'),
    sa.Column('instructions', sa.Text(), nullable=True, comment='Indicaciones para el paciente.'),
    sa.Column('prognosis', sa.Text(), nullable=True, comment='Pronóstico, si aplica.'),
    sa.Column('follow_up_plan', sa.Text(), nullable=True, comment='Plan de seguimiento.'),
    sa.Column('next_appointment_at', sa.DateTime(), nullable=True, comment='Fecha sugerida para próxima cita, con hora si se define.'),
    sa.Column('observations', sa.Text(), nullable=True, comment='Observaciones adicionales.'),
    sa.Column('status', sa.Enum('draft', 'finalized', 'cancelled', name='consultation_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado de la consulta: borrador, finalizada o cancelada.'),
    sa.Column('finalized_by_doctor_id', sa.UUID(), nullable=True, comment='Médico que cerró la consulta.'),
    sa.Column('finalized_at', sa.DateTime(), nullable=True, comment='Fecha y hora de cierre de la consulta.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la consulta.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que inició o registró la consulta.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó la consulta.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Sólo aplicable a borradores no clínicamente finalizados.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la consulta.'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_consultations_appointment_id_appointments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['attending_doctor_id'], ['doctors.id'], name=op.f('fk_consultations_attending_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_consultations_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_consultations_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finalized_by_doctor_id'], ['doctors.id'], name=op.f('fk_consultations_finalized_by_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_consultations_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_consultations_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations')),
    sa.UniqueConstraint('appointment_id', name='uq_consultations_appointment_id')
    )
    op.create_index('ix_consultations_attending_doctor', 'consultations', ['attending_doctor_id'], unique=False)
    op.create_index('ix_consultations_consulted_at', 'consultations', ['consulted_at'], unique=False)
    op.create_index('ix_consultations_patient', 'consultations', ['patient_id'], unique=False)
    op.create_index('ix_consultations_patient_consulted_at', 'consultations', ['patient_id', 'consulted_at'], unique=False)
    op.create_index('ix_consultations_status', 'consultations', ['status'], unique=False)
    op.create_table('clinical_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente al que pertenece el archivo clínico.'),
    sa.Column('consultation_id', sa.UUID(), nullable=True, comment='Consulta relacionada, si aplica.'),
    sa.Column('document_type', sa.Enum('laboratory', 'study', 'image', 'pdf', 'external_prescription', 'clinical_photography', 'consent', 'reference', 'other', name='clinical_document_type', native_enum=False, create_constraint=True), nullable=False, comment='Tipo de archivo clínico.'),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='clinical_document_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado del archivo clínico: activo, archivado o eliminado lógicamente.'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Nombre original del archivo.'),
    sa.Column('file_content', sa.LargeBinary(), nullable=False, comment='Contenido binario del archivo almacenado en PostgreSQL.'),
    sa.Column('mime_type', sa.String(length=160), nullable=False, comment='Tipo MIME del archivo.'),
    sa.Column('size_bytes', sa.Integer(), nullable=False, comment='Tamaño del archivo en bytes.'),
    sa.Column('sha256', sa.String(length=64), nullable=False, comment='Huella SHA-256 para verificar integridad del archivo.'),
    sa.Column('document_date', sa.Date(), nullable=True, comment='Fecha propia del documento, si aplica.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción o contexto del archivo clínico.'),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de carga del archivo clínico.'),
    sa.Column('uploaded_by', sa.UUID(), nullable=True, comment='Usuario que cargó el archivo clínico.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última actualización de metadatos del archivo clínico.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó los metadatos del archivo clínico.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del archivo clínico.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el archivo clínico.'),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_clinical_documents_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_clinical_documents_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_clinical_documents_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_documents_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_clinical_documents_updated_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('fk_clinical_documents_uploaded_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_documents'))
    )
    op.create_index('ix_clinical_documents_consultation', 'clinical_documents', ['consultation_id'], unique=False)
    op.create_index('ix_clinical_documents_patient', 'clinical_documents', ['patient_id'], unique=False)
    op.create_index('ix_clinical_documents_sha256', 'clinical_documents', ['sha256'], unique=False)
    op.create_index('ix_clinical_documents_status', 'clinical_documents', ['status'], unique=False)
    op.create_index('ix_clinical_documents_type', 'clinical_documents', ['document_type'], unique=False)
    op.create_index('ix_clinical_documents_uploaded_at', 'clinical_documents', ['uploaded_at'], unique=False)
    op.create_table('consultation_ai_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Consulta relacionada con el resultado generado por IA.'),
    sa.Column('output_type', sa.Enum('clinical_note', 'summary', 'suggestion', 'instructions_draft', 'other', name='consultation_ai_output_type', native_enum=False, create_constraint=True), nullable=False, comment='Tipo de resultado: nota clínica, resumen, sugerencia, borrador de indicaciones u otro.'),
    sa.Column('content', sa.Text(), nullable=False, comment='Texto generado por el copiloto de IA.'),
    sa.Column('status', sa.Enum('draft', 'approved', 'rejected', name='ai_output_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado de revisión: borrador, aprobado o rechazado.'),
    sa.Column('model_name', sa.String(length=160), nullable=True, comment='Modelo de IA utilizado.'),
    sa.Column('model_version', sa.String(length=160), nullable=True, comment='Versión o configuración relevante del modelo utilizado.'),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='Metadatos técnicos mínimos de la generación.'),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de generación del resultado de IA.'),
    sa.Column('reviewed_by_doctor_id', sa.UUID(), nullable=True, comment='Médico que revisó el resultado generado por IA.'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='Fecha y hora de revisión del resultado generado por IA.'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Motivo de rechazo, si aplica.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro del resultado de IA.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario o proceso que solicitó la generación.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última modificación de estado del resultado de IA.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó el resultado de IA.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica restringida del resultado de IA.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el resultado de IA.'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_consultation_ai_outputs_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_consultation_ai_outputs_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_consultation_ai_outputs_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_doctor_id'], ['doctors.id'], name=op.f('fk_consultation_ai_outputs_reviewed_by_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_consultation_ai_outputs_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_ai_outputs'))
    )
    op.create_index('ix_consultation_ai_outputs_consultation', 'consultation_ai_outputs', ['consultation_id'], unique=False)
    op.create_index('ix_consultation_ai_outputs_generated_at', 'consultation_ai_outputs', ['generated_at'], unique=False)
    op.create_index('ix_consultation_ai_outputs_reviewed_by', 'consultation_ai_outputs', ['reviewed_by_doctor_id'], unique=False)
    op.create_index('ix_consultation_ai_outputs_status', 'consultation_ai_outputs', ['status'], unique=False)
    op.create_index('ix_consultation_ai_outputs_type', 'consultation_ai_outputs', ['output_type'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Consulta origen de la receta.'),
    sa.Column('internal_folio', sa.String(length=80), nullable=False, comment='Folio interno único de la receta.'),
    sa.Column('related_diagnosis_id', sa.UUID(), nullable=True, comment='Diagnóstico relacionado, opcional. Se vinculará cuando exista el modelo de diagnósticos.'),
    sa.Column('observations', sa.Text(), nullable=True, comment='Observaciones generales de la receta.'),
    sa.Column('status', sa.Enum('draft', 'approved', 'voided', name='prescription_status', native_enum=False, create_constraint=True), nullable=False, comment='Estado de la receta: borrador, aprobada o anulada.'),
    sa.Column('doctor_snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='Captura de los datos profesionales del médico al momento de aprobación.'),
    sa.Column('issued_at', sa.DateTime(), nullable=True, comment='Fecha de emisión de la receta.'),
    sa.Column('approved_by_doctor_id', sa.UUID(), nullable=True, comment='Médico que autorizó la receta.'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='Fecha de aprobación de la receta.'),
    sa.Column('voided_at', sa.DateTime(), nullable=True, comment='Fecha de anulación de la receta.'),
    sa.Column('voided_by_doctor_id', sa.UUID(), nullable=True, comment='Médico que anuló la receta.'),
    sa.Column('void_reason', sa.Text(), nullable=True, comment='Motivo de anulación de la receta.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la receta.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que creó el borrador de receta.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última modificación mientras la receta esté en borrador.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que editó la receta.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Eliminación lógica sólo permitida antes de aprobación.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la receta.'),
    sa.ForeignKeyConstraint(['approved_by_doctor_id'], ['doctors.id'], name=op.f('fk_prescriptions_approved_by_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_prescriptions_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_prescriptions_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_prescriptions_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_prescriptions_updated_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by_doctor_id'], ['doctors.id'], name=op.f('fk_prescriptions_voided_by_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions')),
    sa.UniqueConstraint('internal_folio', name='uq_prescriptions_internal_folio')
    )
    op.create_index('ix_prescriptions_approved_by', 'prescriptions', ['approved_by_doctor_id'], unique=False)
    op.create_index('ix_prescriptions_consultation', 'prescriptions', ['consultation_id'], unique=False)
    op.create_index('ix_prescriptions_issued_at', 'prescriptions', ['issued_at'], unique=False)
    op.create_index('ix_prescriptions_related_diagnosis', 'prescriptions', ['related_diagnosis_id'], unique=False)
    op.create_index('ix_prescriptions_status', 'prescriptions', ['status'], unique=False)
    op.create_index('ix_prescriptions_voided_by', 'prescriptions', ['voided_by_doctor_id'], unique=False)
    op.create_table('vital_signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Consulta relacionada con la medición de signos vitales.'),
    sa.Column('measured_at', sa.DateTime(), nullable=False, comment='Fecha y hora de medición de signos vitales.'),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True, comment='Peso en kilogramos.'),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True, comment='Talla en centímetros.'),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1), nullable=True, comment='Temperatura en grados Celsius.'),
    sa.Column('systolic_bp', sa.Integer(), nullable=True, comment='Presión arterial sistólica.'),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True, comment='Presión arterial diastólica.'),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True, comment='Frecuencia cardiaca en latidos por minuto.'),
    sa.Column('respiratory_rate_rpm', sa.Integer(), nullable=True, comment='Frecuencia respiratoria por minuto.'),
    sa.Column('oxygen_saturation', sa.Numeric(precision=5, scale=2), nullable=True, comment='Saturación de oxígeno en porcentaje.'),
    sa.Column('capillary_glucose', sa.Numeric(precision=6, scale=2), nullable=True, comment='Glucosa capilar, si aplica.'),
    sa.Column('pain_scale', sa.Integer(), nullable=True, comment='Escala de dolor de 0 a 10.'),
    sa.Column('observations', sa.Text(), nullable=True, comment='Observaciones sobre la medición.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro de los signos vitales.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró los signos vitales.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última edición, mientras la consulta esté en borrador.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que editó los signos vitales.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica restringida.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente los signos vitales.'),
    sa.CheckConstraint('pain_scale IS NULL OR (pain_scale >= 0 AND pain_scale <= 10)', name=op.f('ck_vital_signs_pain_scale_range')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_vital_signs_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_vital_signs_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_vital_signs_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_vital_signs_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vital_signs'))
    )
    op.create_index('ix_vital_signs_consultation', 'vital_signs', ['consultation_id'], unique=False)
    op.create_index('ix_vital_signs_consultation_measured_at', 'vital_signs', ['consultation_id', 'measured_at'], unique=False)
    op.create_index('ix_vital_signs_measured_at', 'vital_signs', ['measured_at'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False, comment='Receta relacionada con este medicamento.'),
    sa.Column('medication_template_id', sa.UUID(), nullable=True, comment='Plantilla de medicamento usada, opcional. La receta copia los textos y no depende de la plantilla después de emitirse.'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Orden de aparición del medicamento en la receta.'),
    sa.Column('medication_name', sa.String(length=255), nullable=False, comment='Nombre del medicamento.'),
    sa.Column('presentation', sa.String(length=160), nullable=True, comment='Presentación: tabletas, cápsulas, jarabe, ampolletas, etc.'),
    sa.Column('dose', sa.String(length=160), nullable=True, comment='Dosis indicada.'),
    sa.Column('frequency', sa.String(length=160), nullable=True, comment='Frecuencia indicada.'),
    sa.Column('duration', sa.String(length=160), nullable=True, comment='Duración del tratamiento.'),
    sa.Column('instructions', sa.Text(), nullable=True, comment='Indicaciones específicas del medicamento.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del medicamento de receta.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que capturó el medicamento.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última edición mientras la receta esté en borrador.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que editó el medicamento.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Eliminación lógica sólo permitida antes de aprobación.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el medicamento de receta.'),
    sa.CheckConstraint('position > 0', name=op.f('ck_prescription_items_position_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_prescription_items_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_prescription_items_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medication_template_id'], ['medication_templates.id'], name=op.f('fk_prescription_items_medication_template_id_medication_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_prescription_items_prescription_id_prescriptions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_prescription_items_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription_items')),
    sa.UniqueConstraint('prescription_id', 'position', name='uq_prescription_items_prescription_position')
    )
    op.create_index('ix_prescription_items_medication_template', 'prescription_items', ['medication_template_id'], unique=False)
    op.create_index('ix_prescription_items_prescription', 'prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prescription_items_prescription', table_name='prescription_items')
    op.drop_index('ix_prescription_items_medication_template', table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index('ix_vital_signs_measured_at', table_name='vital_signs')
    op.drop_index('ix_vital_signs_consultation_measured_at', table_name='vital_signs')
    op.drop_index('ix_vital_signs_consultation', table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index('ix_prescriptions_voided_by', table_name='prescriptions')
    op.drop_index('ix_prescriptions_status', table_name='prescriptions')
    op.drop_index('ix_prescriptions_related_diagnosis', table_name='prescriptions')
    op.drop_index('ix_prescriptions_issued_at', table_name='prescriptions')
    op.drop_index('ix_prescriptions_consultation', table_name='prescriptions')
    op.drop_index('ix_prescriptions_approved_by', table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_consultation_ai_outputs_type', table_name='consultation_ai_outputs')
    op.drop_index('ix_consultation_ai_outputs_status', table_name='consultation_ai_outputs')
    op.drop_index('ix_consultation_ai_outputs_reviewed_by', table_name='consultation_ai_outputs')
    op.drop_index('ix_consultation_ai_outputs_generated_at', table_name='consultation_ai_outputs')
    op.drop_index('ix_consultation_ai_outputs_consultation', table_name='consultation_ai_outputs')
    op.drop_table('consultation_ai_outputs')
    op.drop_index('ix_clinical_documents_uploaded_at', table_name='clinical_documents')
    op.drop_index('ix_clinical_documents_type', table_name='clinical_documents')
    op.drop_index('ix_clinical_documents_status', table_name='clinical_documents')
    op.drop_index('ix_clinical_documents_sha256', table_name='clinical_documents')
    op.drop_index('ix_clinical_documents_patient', table_name='clinical_documents')
    op.drop_index('ix_clinical_documents_consultation', table_name='clinical_documents')
    op.drop_table('clinical_documents')
    op.drop_index('ix_consultations_status', table_name='consultations')
    op.drop_index('ix_consultations_patient_consulted_at', table_name='consultations')
    op.drop_index('ix_consultations_patient', table_name='consultations')
    op.drop_index('ix_consultations_consulted_at', table_name='consultations')
    op.drop_index('ix_consultations_attending_doctor', table_name='consultations')
    op.drop_table('consultations')
    op.drop_table('platform_setup')
    op.drop_index('ix_patient_clinical_items_type', table_name='patient_clinical_items')
    op.drop_index('ix_patient_clinical_items_status', table_name='patient_clinical_items')
    op.drop_index('ix_patient_clinical_items_patient_type_status', table_name='patient_clinical_items')
    op.drop_index('ix_patient_clinical_items_patient', table_name='patient_clinical_items')
    op.drop_table('patient_clinical_items')
    op.drop_index('ix_medication_templates_status', table_name='medication_templates')
    op.drop_index('ix_medication_templates_medication_name', table_name='medication_templates')
    op.drop_index('ix_medication_templates_doctor', table_name='medication_templates')
    op.drop_table('medication_templates')
    op.drop_index('uq_medical_history_versions_current_patient', table_name='medical_history_versions', postgresql_where=sa.text("status = 'current' AND deleted_at IS NULL"))
    op.drop_index('ix_medical_history_versions_status', table_name='medical_history_versions')
    op.drop_index('ix_medical_history_versions_reviewed_by', table_name='medical_history_versions')
    op.drop_index('ix_medical_history_versions_patient', table_name='medical_history_versions')
    op.drop_table('medical_history_versions')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_scheduled_date', table_name='appointments')
    op.drop_index('ix_appointments_rescheduled_from', table_name='appointments')
    op.drop_index('ix_appointments_patient', table_name='appointments')
    op.drop_index('ix_appointments_doctor_date_time', table_name='appointments')
    op.drop_index('ix_appointments_doctor', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('uq_patients_curp_active', table_name='patients', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_patients_status', table_name='patients')
    op.drop_index('ix_patients_full_name', table_name='patients')
    op.drop_index('ix_patients_created_at', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_doctors_status', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_audit_events_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_user', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
