"""ai_provider_credential

Revision ID: 719e7bc0e584
Revises: 9c1f4d7b2a06
Create Date: 2026-06-27 23:24:57.256835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719e7bc0e584'
down_revision: Union[str, Sequence[str], None] = '9c1f4d7b2a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Usuario dueño de la credencial.'),
    sa.Column('provider', sa.Enum('opencode_zen', 'opencode_go', 'openai', 'anthropic', 'gemini', 'openrouter', 'ollama', name='ai_provider', native_enum=False, create_constraint=True), nullable=False, comment='Proveedor de IA de la credencial.'),
    sa.Column('label', sa.String(length=120), nullable=False, comment='Etiqueta legible elegida por el usuario para identificar la credencial.'),
    sa.Column('secret_encrypted', sa.Text(), nullable=False, comment='Secreto del proveedor cifrado con Fernet (NUNCA el claro).'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Si la credencial está habilitada para usarse.'),
    sa.Column('default_model', sa.String(length=160), nullable=True, comment='Modelo por defecto sugerido para esta credencial.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la credencial.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que creó la credencial.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última actualización de la credencial.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó la credencial.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la credencial.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la credencial.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_ai_provider_credentials_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_ai_provider_credentials_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_ai_provider_credentials_updated_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ai_provider_credentials_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_provider_credentials'))
    )
    op.create_index('ix_ai_provider_credentials_provider', 'ai_provider_credentials', ['provider'], unique=False)
    op.create_index('ix_ai_provider_credentials_user', 'ai_provider_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_provider_credentials_user', table_name='ai_provider_credentials')
    op.drop_index('ix_ai_provider_credentials_provider', table_name='ai_provider_credentials')
    op.drop_table('ai_provider_credentials')
    # ### end Alembic commands ###
