"""add patient_immunizations table

Revision ID: 7c87bb5c5dd9
Revises: b43f04cf2332
Create Date: 2026-06-28 22:15:02.576456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c87bb5c5dd9'
down_revision: Union[str, Sequence[str], None] = 'b43f04cf2332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_immunizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente al que pertenece la inmunización.'),
    sa.Column('vaccine_name', sa.String(length=255), nullable=False, comment="Nombre de la vacuna (p. ej. 'Influenza estacional', 'Hepatitis B')."),
    sa.Column('dose_number', sa.Integer(), nullable=True, comment='Número de dosis aplicada (1ª, 2ª, refuerzo…), si aplica.'),
    sa.Column('administered_on', sa.Date(), nullable=True, comment='Fecha de aplicación de la vacuna, si se conoce.'),
    sa.Column('status', sa.Enum('aplicada', 'no_aplicada', 'contraindicada', name='immunization_status', native_enum=False, create_constraint=True), server_default='aplicada', nullable=False, comment='Estado del registro: aplicada, no aplicada o contraindicada.'),
    sa.Column('route', sa.Enum('intramuscular', 'subcutanea', 'intradermica', 'oral', 'intranasal', name='immunization_route', native_enum=False, create_constraint=True), nullable=True, comment='Vía de administración (intramuscular, subcutánea, oral, etc.), si aplica.'),
    sa.Column('lot_number', sa.String(length=100), nullable=True, comment='Número de lote del biológico, si se conoce.'),
    sa.Column('site', sa.String(length=120), nullable=True, comment="Sitio anatómico de aplicación (p. ej. 'deltoides izquierdo'), si aplica."),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas o contexto adicional de la inmunización (opcional).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro de la inmunización.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró la inmunización.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó la inmunización.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la inmunización.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la inmunización.'),
    sa.CheckConstraint('dose_number IS NULL OR (dose_number >= 1 AND dose_number <= 50)', name=op.f('ck_patient_immunizations_patient_immunization_dose_number_range')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_patient_immunizations_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_patient_immunizations_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_immunizations_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_patient_immunizations_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_immunizations'))
    )
    op.create_index('ix_patient_immunizations_administered_on', 'patient_immunizations', ['administered_on'], unique=False)
    op.create_index('ix_patient_immunizations_patient', 'patient_immunizations', ['patient_id'], unique=False)
    op.create_index('ix_patient_immunizations_patient_administered', 'patient_immunizations', ['patient_id', 'administered_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patient_immunizations_patient_administered', table_name='patient_immunizations')
    op.drop_index('ix_patient_immunizations_patient', table_name='patient_immunizations')
    op.drop_index('ix_patient_immunizations_administered_on', table_name='patient_immunizations')
    op.drop_table('patient_immunizations')
    # ### end Alembic commands ###
