"""add clinical_events and patient pregnancy

Revision ID: 84413285ba37
Revises: 16a708925935
Create Date: 2026-06-28 15:20:01.223526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84413285ba37'
down_revision: Union[str, Sequence[str], None] = '16a708925935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente al que pertenece el evento clínico.'),
    sa.Column('event_type', sa.Enum('hospitalization', 'emergency', 'referral', 'procedure', 'other', name='clinical_event_type', native_enum=False, create_constraint=True), nullable=False, comment='Tipo de evento: hospitalización, urgencia, referencia, procedimiento u otro.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título breve del evento clínico.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción o contexto del evento.'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='Fecha y hora de inicio del evento.'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='Fecha y hora de fin del evento, si concluyó.'),
    sa.Column('severity', sa.Enum('low', 'moderate', 'high', 'critical', name='clinical_severity', native_enum=False, create_constraint=True), nullable=True, comment='Severidad del evento (baja, moderada, alta o crítica), si aplica.'),
    sa.Column('specialty', sa.String(length=255), nullable=True, comment='Especialidad relacionada (p. ej. en una referencia).'),
    sa.Column('destination', sa.String(length=255), nullable=True, comment='Destino del evento (p. ej. a quién/dónde se refiere al paciente).'),
    sa.Column('status', sa.Enum('active', 'resolved', 'cancelled', name='clinical_event_status', native_enum=False, create_constraint=True), nullable=True, comment='Estado del evento: activo, resuelto o cancelado, si aplica.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro del evento.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró el evento.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó el evento.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del evento.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el evento.'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_clinical_events_clinical_event_dates')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_clinical_events_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_clinical_events_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_events_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_clinical_events_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_events'))
    )
    op.create_index('ix_clinical_events_patient', 'clinical_events', ['patient_id'], unique=False)
    op.create_index('ix_clinical_events_patient_started_at', 'clinical_events', ['patient_id', 'started_at'], unique=False)
    op.create_index('ix_clinical_events_started_at', 'clinical_events', ['started_at'], unique=False)
    op.create_index('ix_clinical_events_type', 'clinical_events', ['event_type'], unique=False)
    op.add_column('patients', sa.Column('pregnancy_status', sa.Enum('none', 'pregnant', 'postpartum', 'lactating', name='pregnancy_status', native_enum=False, create_constraint=True), server_default='none', nullable=False, comment='Estado de embarazo/lactancia: none, pregnant, postpartum o lactating.'))
    op.add_column('patients', sa.Column('pregnancy_since', sa.Date(), nullable=True, comment='Fecha de inicio del embarazo/estado, si aplica.'))
    op.add_column('patients', sa.Column('estimated_due_date', sa.Date(), nullable=True, comment='Fecha probable de parto, si aplica.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'estimated_due_date')
    op.drop_column('patients', 'pregnancy_since')
    op.drop_column('patients', 'pregnancy_status')
    op.drop_index('ix_clinical_events_type', table_name='clinical_events')
    op.drop_index('ix_clinical_events_started_at', table_name='clinical_events')
    op.drop_index('ix_clinical_events_patient_started_at', table_name='clinical_events')
    op.drop_index('ix_clinical_events_patient', table_name='clinical_events')
    op.drop_table('clinical_events')
    # ### end Alembic commands ###
