"""add clinical codes and diagnosis code reference

Revision ID: 8d959cf82c8e
Revises: b6a5560f8f20
Create Date: 2026-06-28 17:11:50.857662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d959cf82c8e'
down_revision: Union[str, Sequence[str], None] = 'b6a5560f8f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system', sa.Enum('cie10', 'loinc', 'atc', name='clinical_code_system', native_enum=False, create_constraint=True), nullable=False, comment='Sistema de codificación: cie10 (diagnósticos), loinc (laboratorio) o atc (medicamentos).'),
    sa.Column('code', sa.String(length=64), nullable=False, comment="Código real dentro del sistema (p. ej. 'E11.9' en CIE-10, '4548-4' en LOINC)."),
    sa.Column('display_term', sa.String(length=512), nullable=False, comment='Término legible en español asociado al código (campo de búsqueda).'),
    sa.Column('parent_code', sa.String(length=64), nullable=True, comment='Código padre dentro del mismo sistema, si el código pertenece a una jerarquía.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro del código.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró el código.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última actualización del código.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó el código.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del código.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el código.'),
    sa.CheckConstraint('length(trim(code)) > 0', name=op.f('ck_clinical_codes_clinical_code_not_blank')),
    sa.CheckConstraint('length(trim(display_term)) > 0', name=op.f('ck_clinical_codes_clinical_code_display_term_not_blank')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_clinical_codes_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_clinical_codes_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_clinical_codes_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_codes'))
    )
    op.create_index('ix_clinical_codes_system', 'clinical_codes', ['system'], unique=False)
    op.create_index('uq_clinical_codes_system_code_active', 'clinical_codes', ['system', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('consultation_diagnoses', sa.Column('clinical_code_id', sa.UUID(), nullable=True, comment='Código clínico validado (CIE-10) del catálogo, vinculado al diagnóstico si se eligió uno.'))
    op.create_foreign_key(op.f('fk_consultation_diagnoses_clinical_code_id_clinical_codes'), 'consultation_diagnoses', 'clinical_codes', ['clinical_code_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_consultation_diagnoses_clinical_code_id_clinical_codes'), 'consultation_diagnoses', type_='foreignkey')
    op.drop_column('consultation_diagnoses', 'clinical_code_id')
    op.drop_index('uq_clinical_codes_system_code_active', table_name='clinical_codes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_clinical_codes_system', table_name='clinical_codes')
    op.drop_table('clinical_codes')
    # ### end Alembic commands ###
