"""add conversations and messages tables

Revision ID: 91a7375c266c
Revises: 7c87bb5c5dd9
Create Date: 2026-06-29 01:39:27.050148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91a7375c266c'
down_revision: Union[str, Sequence[str], None] = '7c87bb5c5dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True, comment='Paciente del chat; NULO para el chat global (tareas sin paciente).'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='Título breve de la conversación (opcional).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la conversación.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que creó la conversación.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última actividad/edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó la conversación.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la conversación.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la conversación.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_conversations_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_conversations_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_conversations_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_conversations_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_created_by', 'conversations', ['created_by'], unique=False)
    op.create_index('ix_conversations_patient', 'conversations', ['patient_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Conversación a la que pertenece el mensaje.'),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='message_role', native_enum=False, create_constraint=True), nullable=False, comment='Rol del autor: user, assistant, system o tool.'),
    sa.Column('content', sa.Text(), server_default='', nullable=False, comment='Contenido textual del mensaje.'),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='Payload estructurado opcional (tool calls / metadatos del turno).'),
    sa.Column('sequence_index', sa.Integer(), server_default='0', nullable=False, comment='Orden del mensaje dentro de la conversación (ascendente).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del mensaje.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró el mensaje.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó el mensaje.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del mensaje.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el mensaje.'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_messages_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_messages_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_messages_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_sequence', 'messages', ['conversation_id', 'sequence_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_sequence', table_name='messages')
    op.drop_index('ix_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_patient', table_name='conversations')
    op.drop_index('ix_conversations_created_by', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
