"""add patient_history_items table

Revision ID: b43f04cf2332
Revises: f0710da0bf95
Create Date: 2026-06-28 21:56:45.400310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43f04cf2332'
down_revision: Union[str, Sequence[str], None] = 'f0710da0bf95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_history_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Paciente al que pertenece el antecedente.'),
    sa.Column('category', sa.Enum('familiar', 'quirurgico', 'obstetrico', 'patologico', 'no_patologico', name='patient_history_item_category', native_enum=False, create_constraint=True), nullable=False, comment='Categoría del antecedente: familiar, quirúrgico, obstétrico, patológico o no patológico.'),
    sa.Column('description', sa.String(length=255), nullable=False, comment="Descripción breve del antecedente (p. ej. 'Apendicectomía', 'Diabetes en la madre')."),
    sa.Column('relationship_to_patient', sa.Enum('padre', 'madre', 'hermano', 'hermana', 'abuelo', 'abuela', 'hijo', 'hija', 'otro', name='family_relationship', native_enum=False, create_constraint=True), nullable=True, comment='Parentesco del familiar, para antecedentes familiares (opcional).'),
    sa.Column('related_condition', sa.String(length=255), nullable=True, comment='Condición o diagnóstico relacionado, en texto libre (opcional).'),
    sa.Column('related_code', sa.String(length=64), nullable=True, comment='Código de la condición relacionada (estilo CIE-10), si se conoce (opcional).'),
    sa.Column('onset_age', sa.Integer(), nullable=True, comment='Edad (años) de inicio o del evento, si se conoce (opcional).'),
    sa.Column('occurred_on', sa.Date(), nullable=True, comment='Fecha del evento (p. ej. de la cirugía), si se conoce (opcional).'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas o contexto adicional del antecedente (opcional).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de registro del antecedente.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que registró el antecedente.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó el antecedente.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica del antecedente.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente el antecedente.'),
    sa.CheckConstraint('onset_age IS NULL OR (onset_age >= 0 AND onset_age <= 120)', name=op.f('ck_patient_history_items_patient_history_item_onset_age_range')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_patient_history_items_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_patient_history_items_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_history_items_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_patient_history_items_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_history_items'))
    )
    op.create_index('ix_patient_history_items_category', 'patient_history_items', ['category'], unique=False)
    op.create_index('ix_patient_history_items_patient', 'patient_history_items', ['patient_id'], unique=False)
    op.create_index('ix_patient_history_items_patient_category', 'patient_history_items', ['patient_id', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patient_history_items_patient_category', table_name='patient_history_items')
    op.drop_index('ix_patient_history_items_patient', table_name='patient_history_items')
    op.drop_index('ix_patient_history_items_category', table_name='patient_history_items')
    op.drop_table('patient_history_items')
    # ### end Alembic commands ###
