"""add institutional settings

Revision ID: b6a5560f8f20
Revises: 6bb02a84ca2a
Create Date: 2026-06-28 16:35:37.540311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6a5560f8f20'
down_revision: Union[str, Sequence[str], None] = '6bb02a84ca2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False, comment="Clave única de la configuración (p. ej. 'vital_redflag.systolic_bp')."),
    sa.Column('category', sa.Enum('vital_threshold', 'lab_target', 'follow_up', 'protocol', name='setting_category', native_enum=False, create_constraint=True), nullable=False, comment='Categoría/ámbito de la configuración: vital_threshold, lab_target, follow_up o protocol.'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Valor JSON de la configuración; su forma depende de la categoría.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Descripción en español de la configuración y el valor por defecto razonado.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la configuración.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que creó la configuración.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última actualización de la configuración.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó la configuración.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la configuración.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la configuración.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_institutional_settings_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_institutional_settings_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_institutional_settings_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutional_settings'))
    )
    op.create_index('ix_institutional_settings_category', 'institutional_settings', ['category'], unique=False)
    op.create_index('uq_institutional_settings_key_active', 'institutional_settings', ['key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_institutional_settings_key_active', table_name='institutional_settings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_institutional_settings_category', table_name='institutional_settings')
    op.drop_table('institutional_settings')
    # ### end Alembic commands ###
